WebApplication/Controllers/ThesesController.cs
namespace WebApplication.Controllers
{
    #region usings
    using Microsoft.AspNetCore.Mvc;
    using PagedList;
    using BusinessCore.Abstract;
    using Data.Db;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using WebApplication.Models;
    using Data.Models.DTOs;
    using Data.Models;
    using System.Linq;
    using System.Dynamic;
    #endregion
    public class ThesesController : Controller
    {
        private readonly IThesisService _thesisService;
        private readonly IInstituteService _instituteService;
        private readonly IUniversityService _universityService;
        private ThesesContext db = new ThesesContext();

        public ThesesController(IThesisService thesisService , IInstituteService instituteService , IUniversityService universityService)
        {
            _thesisService = thesisService;
            _instituteService = instituteService;
            _universityService = universityService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            try
            {
                var result = _thesisService.GetAll();
                if (result.IsSuccess)
                {
                    return View(result.Data);
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        
        [HttpPost]
        public IActionResult GetByNumber(string thesisNumber)
        {
            try
            {
                List<Thesis> theses = new List<Thesis>();
                var result = _thesisService.GetByNumber(Convert.ToInt32(thesisNumber));
                theses.Add(result.Data);
                if (result.IsSuccess)
                {
                    return View("Index",theses);
                }
                return View("Index", null);

            }
            catch (Exception ex)
            {
                return PartialView(ex.Message);
            }
        }
        [HttpGet]
        public IActionResult Filter()
        {
            var thesisModel = new ThesisModel();

            List<SelectListItem> universities;
            List<SelectListItem> institutes;
            universities = _universityService.List().Data.Select(i => new SelectListItem
            {
                Text = i.NAME.ToString(),
                Value = i.UNIVERSITYID.ToString()

            }).ToList();

            institutes = _instituteService.List().Data.Select(i => new SelectListItem
            {
                Text = i.NAME.ToString(),
                Value = i.INSTITUTEID.ToString()
            }).ToList();

            ViewBag.Universities = universities;
            ViewBag.Institutes = institutes;
            return View(thesisModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Filter(ThesisModel thesisModel)
        {
            var result = _thesisService.GetFilter(thesisModel);
            if (result.IsSuccess)
            {
                return View("Index",result.Data);
            }
            return View();
        }
        [HttpGet]
        public JsonResult GetData(int number)
        {
            try
            {
                var result = _thesisService.GetByNumber(number);
                if (result.Data != null)
                {
                    return Json(new { success = result.IsSuccess, message = result.Message , thesis = result.Data });
                }
                return Json(new { success = result.IsSuccess, message = result.Message });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThesesApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/theses/index">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/theses/filter">Detail Filter</a>
                    </li>
                    <li>
                        <form class="form-inline my-2 my-lg-0 ml-auto" action="@Url.Action("logout", "account")" method="post">

                            <div class="form-group">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">LogOut</button>
                            </div>
                        </form>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/account/login">User Login</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 ml-auto" action="@Url.Action("GetByNumber", "Theses")" method="post">
                    <div class="form-group">
                        <input name="thesisNumber" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)`
</body>
</html>